config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resource :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index] do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#followed', as: 'follows'
  	get 'followers' => 'relationships#follower', as: 'followers'
  end
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
end

app/models/book.rb
class Book < ApplicationRecord

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user?, only: [:edit]

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
    @comments = @item.comments.order(created_at: :desc)
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
    @user = @book.user
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(@book), notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end



  private

  def current_user?
    unless  Book.find(params[:id]).user == current_user
      redirect_to books_path
    end
  end

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<% if book.errors.any? %>
		<div id="error_explanation">
			<h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
			<ul>
				<% book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="5"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
							<li>
    					<%= link_to book_favorites_path(book), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    					<%= book.favorites.count %> いいね
  						<% end %>
							</li>
						<% else %>
							<li>
    						<%= link_to book_favorites_path(book), method: :post do %>
    						<i class="fa fa-heart-o" aria-hidden="true"></i>
    						<%= book.favorites.count %> いいね
    						<% end %>
							</li>
						<% end %>
					</td>
					<td><%= link_to "コメント数：#{book.book_comments.count}", book_path(book) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td>
						<% if @book.favorited_by?(current_user) %>
							<li>
    					<%= link_to book_favorites_path(@book), method: :delete do %>
    					<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    					<%= @book.favorites.count %> いいね
  						<% end %>
							</li>
						<% else %>
							<li>
    						<%= link_to book_favorites_path(@book), method: :post do %>
    						<i class="fa fa-heart-o" aria-hidden="true"></i>
    						<%= @book.favorites.count %> いいね
    						<% end %>
							</li>
						<% end %>
					</td>
					<td><%= link_to "コメント数：#{@book.book_comments.count}", book_path(@book) %></td>
					<% if @user.id == current_user.id %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<% @book.book_comments.each do |book_comment| %>
				<table class="comment">
					<tr>
						<td><%=link_to book_comment.user.name, user_path(@user) %></td>
 						<td><%= book_comment.comment %></td>
						<% if book_comment.user == current_user %>
							<td><%= link_to "Destroy", book_book_comments_path(book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@comment.id}" %></td>
						<% end %>
					</tr>
				 </table>
	 	 	<% end %>

			<% if @comment.errors.any? %>
				<div id="error_explanation">
					<h2><%= @comment.errors.count %>errors commented this obj from being saved:</h2>
					<ul>
						<% @comment.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<%= form_for [@book, @comment] do |f| %>
    		<div class="row">
        	<div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        	</div>
    		</div>
    		<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			</li>
			<% end %>
	</div>
</div>